FROM informaticsmatters/rdock:2013.1.2
MAINTAINER Tim Dudgeon

USER root

RUN yum -y install java-1.8.0-openjdk-headless.x86_64 &&\
 yum clean all 
 
ENV JAVA_HOME /usr/lib/jvm/jre-openjdk/

# get nextflow
WORKDIR /tmp
RUN curl -fsSL get.nextflow.io | bash && chmod 755 nextflow &&\
  mv nextflow /usr/local/bin

USER rdock
WORKDIR /home/rdock
